/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FiboRouteImport } from './routes/fibo'
import { Route as LazyMemoryRouteImport } from './routes/lazy-memory'
import { Route as NatechRouteImport } from './routes/natech'
import { Route as SdkRouteImport } from './routes/sdk'
import { Route as StackRouteImport } from './routes/stack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FiboRoute = FiboRouteImport.update({
  id: '/fibo',
  path: '/fibo',
  getParentRoute: () => rootRouteImport,
} as any)
const LazyMemoryRoute = LazyMemoryRouteImport.update({
  id: '/lazy-memory',
  path: '/lazy-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const NatechRoute = NatechRouteImport.update({
  id: '/natech',
  path: '/natech',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkRoute = SdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fibo': typeof FiboRoute
  '/lazy-memory': typeof LazyMemoryRoute
  '/natech': typeof NatechRoute
  '/sdk': typeof SdkRoute
  '/stack': typeof StackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fibo': typeof FiboRoute
  '/lazy-memory': typeof LazyMemoryRoute
  '/natech': typeof NatechRoute
  '/sdk': typeof SdkRoute
  '/stack': typeof StackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/fibo': typeof FiboRoute
  '/lazy-memory': typeof LazyMemoryRoute
  '/natech': typeof NatechRoute
  '/sdk': typeof SdkRoute
  '/stack': typeof StackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/fibo'
    | '/lazy-memory'
    | '/natech'
    | '/sdk'
    | '/stack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/fibo'
    | '/lazy-memory'
    | '/natech'
    | '/sdk'
    | '/stack'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/fibo'
    | '/lazy-memory'
    | '/natech'
    | '/sdk'
    | '/stack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FiboRoute: typeof FiboRoute
  LazyMemoryRoute: typeof LazyMemoryRoute
  NatechRoute: typeof NatechRoute
  SdkRoute: typeof SdkRoute
  StackRoute: typeof StackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fibo': {
      id: '/fibo'
      path: '/fibo'
      fullPath: '/fibo'
      preLoaderRoute: typeof FiboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lazy-memory': {
      id: '/lazy-memory'
      path: '/lazy-memory'
      fullPath: '/lazy-memory'
      preLoaderRoute: typeof LazyMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/natech': {
      id: '/natech'
      path: '/natech'
      fullPath: '/natech'
      preLoaderRoute: typeof NatechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk': {
      id: '/sdk'
      path: '/sdk'
      fullPath: '/sdk'
      preLoaderRoute: typeof SdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FiboRoute: FiboRoute,
  LazyMemoryRoute: LazyMemoryRoute,
  NatechRoute: NatechRoute,
  SdkRoute: SdkRoute,
  StackRoute: StackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
